# config/packages/translation.yaml
framework:
    default_locale: fr  # Changez cela à 'fr' pour le français
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: 
            - fr  # Utilisez 'fr' comme fallback
